#!/usr/bin/env python
#
# Copyright (c) Microsoft.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#----------------------

import socket
import sys
from time import sleep

if  len(sys.argv) != 3:
    print "usage listen_host listen_port"
    exit(1)
# Create a UDP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
name=sock.getsockname()

HOST = sys.argv[1]
PORT = int(sys.argv[2])
HOST_PORT=HOST+","+str(PORT)
server_address = (HOST, PORT)

counter=0
while True:
    counter += 1
    try:
        # Send data
        print "count:"+str(counter)+"\t"
        message="client-message-count="+str(counter)
	print "message:"+message
        sent = sock.sendto(message, server_address)
        print "send result:"+str(sent)
        print "sleeping ..."
        sleep(1)
    except socket.error as msg:
        print 'Send error: ' + str(msg[0]) + ' Message ' + msg[1]
        sys.exit(1)    
