#!/usr/bin/env python
#
# Copyright (c) Microsoft.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#--------------------------------------------------------------------------

import sys
import socket
import os
from time import sleep


if  len(sys.argv) != 3:
    print "usage listen_host listen_port"
    exit(1)

HOST = sys.argv[1]
PORT = int(sys.argv[2])
HOST_PORT=HOST+","+str(PORT)

node=os.getenv('MY_NODE_NAME')
pod=os.getenv('MY_POD_NAME')
podIP=os.getenv('MY_POD_IP')

logPrefix="node="+node+ " pod="+pod+ " podIP="+podIP

print logPrefix+" udp_server host port:"+str(HOST_PORT)

sock = socket.socket(socket.AF_INET,socket.SOCK_DGRAM) # UDP
print logPrefix+" Going to bind ..."
sock.bind((HOST, PORT))
print logPrefix+" Socket bound"
counter=0


while True:
    counter += 1
    try:
        data, addr = sock.recvfrom(1024) # buffer size is 1024 bytes
        print logPrefix+" count="+str(counter)+" src-addr="+str(addr)+" received-msg="+str(data)
    except socket.error as msg:
        print logPrefix+' receive failed. Error Code : ' + str(msg[0]) + ' Message ' + msg[1]
